### PR TITLE
Checks if it is alphanum

### PR DESCRIPTION
**Pull request by DevBefell**

### CODE REVIEW

**Comment by SecretPanda420** [comment]
I don't see anyone typing in not-alphanumeric, even if they do it would probably be like 1 in a thousand times if not zero. This also has one more problem that it does not check for underscores in names. I feel like this is not very needed and would slow down the process than it already is. @mew @PyICoder

**Comment by mew** [comment]
> I don't see anyone typing in not-alphanumeric, even if they do it would probably be like 1 in a thousand times if not zero. This also has one more problem that it does not check for underscores in names. I feel like this is not very needed and would slow down the process than it already is. @mew @PyICoder

I don't really think its a huge issue. I imagine well over 90% of the time getting a player's stats is waiting for a response from the Hypixel API. The amount of time it takes to check if the name is alphanumeric is less than a tenth of a second. There is no way the average user notices this time loss.
If we _really_ cared about performance, [we wouldnt be using Gson](https://blog.overops.com/the-ultimate-json-library-json-simple-vs-gson-vs-jackson-vs-json/).

**Comment by SecretPanda420** [comment]
> I don't really think its a huge issue. I imagine well over 90% of the time getting a player's stats is waiting for a response from the Hypixel API. The amount of time it takes to check if the name is alphanumeric is less than a tenth of a second. There is no way the average user notices this time loss.
> If we _really_ cared about performance, [we wouldnt be using Gson](https://blog.overops.com/the-ultimate-json-library-json-simple-vs-gson-vs-jackson-vs-json/).

Yeah i guess so, but still realistically speaking i dont think anyone would type in non-alphanumeric names anyway but go ahead if you think its useful enough(also add a support for underscores in names). 😅

P.S. I added Gson because I thought it'd be more future proof if we decide to add more configs in the future, also it just takes the key once out during startup so i dont think it affects performance much anyway.

**Comment by DevBefell** [comment]
I understand thanks.

**Pull request merged**
